apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: micro-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: tochratana/spring-micro-product-service:v1.0.0
          ports:
            - containerPort: 8383
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: micro-demo
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8383
      targetPort: 8383
  type: ClusterIP