apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: micro-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: tochratana/spring-micro-product-service:latest
          ports:
            - containerPort: 8080