apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Staging server (no rate limits, untrusted certs)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: it.tochratana@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-account-key

    solvers:
      - http01:
          ingress:
            class: nginx