# container information about machines that we use ansible to control
[local]
localhost ansible_connection=local

[masters]
master1 ansible_host=136.110.22.213 ansible_user=tochratana

[workers]
worker1 ansible_host=136.110.19.144 ansible_user=tochratana