# 1. The Database Service (This is the name your backend will look for!)
apiVersion: v1
kind: Service
metadata:
  name: x  # <-- THIS REPLACES "localhost"
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
# 2. The Database Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        image: postgres:17
        env:
        - name: POSTGRES_USER
          value: "tochratana"
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "jobseek"