[all:vars]
ansible_user=tochratana
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[local]
localhost ansible_connection=local

[masters]
master02 ansible_host=34.87.166.203
master03 ansible_host=35.198.233.181


[workers]
worker01 ansible_host=34.96.160.20
worker02 ansible_host=34.150.125.171
