apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-fileupload-dpl
spec: 
  selector:
    matchLabels:
      app: spring-fileupload-app
  template:
    metadata:
      labels:
        app: spring-fileupload-app
    spec:
      containers:
      - name: spring-fileupload-app
        image: 69966/springgradleimg:1.1.1
        ports:
        - containerPort: 8080
        volumeMounts: 
          - name: spring-vol 
            mountPath: /app/src/main/resources/images
      volumes: 
        - name: spring-vol 
          persistentVolumeClaim: 
            claimName: spring-fileupload-pvc