#!/bin/bash

create-instance: 
  echo "Create first google instance with ssh pub key"
  ansible-playbook playbooks/create-gcp-instance.yaml

destoy-instance:
  echo "Delete vm"
  ansible-playbook playbooks/destroy-gcp-instance.yaml