# This inventory describe a HA typology with stacked etcd (== same nodes as control plane)
# and 3 worker nodes
# See https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
# for tips on building your # inventory

# Configure 'ip' variable to bind kubernetes services on a different ip than the default iface
# We should set etcd_member_name for etcd cluster. The node that are not etcd members do not need to set the value,
# or can set the empty string value.


[all:vars]
ansible_user=tochratana
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
# ansible_python_interpreter=/usr/bin/python3 # for hide interpreter warning when ping command



[kube_control_plane]
node1 ansible_host=34.31.30.68  # ip=10.3.0.1 etcd_member_name=etcd1 # master01
node2 ansible_host=34.87.70.98  # ip=10.3.0.2 etcd_member_name=etcd2 # master 02
node3 ansible_host=35.186.149.235  # ip=10.3.0.3 etcd_member_name=etcd3 # master 03

[etcd:children]
kube_control_plane

[kube_node]
node4 ansible_host=34.150.48.104  # ip=10.3.0.4 # worker01
node5 ansible_host=34.92.247.6  # ip=10.3.0.5 # worker02
# node6 ansible_host=95.54.0.17  # ip=10.3.0.6
