[local]
localhost ansible_connection=local

[dev]
dev1 ansible_host=34.143.151.177 ansible_user=tochratana ; Worker 1

[prod]
prod1 ansible_host=34.1.135.199 ansible_user=tochratana ; Worker 2

[all:children]
local
dev
prod