[local]
localhost ansible_connection=local

[dev]
dev1 ansible_host=136.110.22.213 ansible_user=tochratana


[prod]
prod1 ansible_host=136.110.19.144 ansible_user=tochratana

[all:children]
local
dev
prod
