[all:vars]
ansible_user=tochratana
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[local]
localhost ansible_connection=local

[masters]
master01 ansible_host=35.240.128.38
master02 ansible_host=35.238.89.243
master03 ansible_host=34.165.195.82


[workers]
worker01 ansible_host=34.19.240.66
worker02 ansible_host=34.18.139.76
