[all:vars]
ansible_user=tochratana


[nfs-servers]
node1 ansible_user=tochratana ansible_host=136.110.22.213

[nfs-clients]
node2 ansible_user=tochratana ansible_host=136.110.19.144
node3 ansible_user=tochratana ansible_host=34.143.151.177

[all:children]
nfs-servers
nfs-clients