- name: Install Common Service Playbook
  hosts: workers
  become: true
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
    - name: istall neofetch
      apt: 
        name: neofetch
        state: present
