apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo-pod
  labels: 
    app: nginx-demo-lbl
spec: 
  containers: 
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80