nfs_server:
  ip: 10.148.0.6
  mount_path: /srv/nfs_shared

nfs_clients:
  mount_path: /mnt/nfs_shared
  ips:
    - 10.148.0.7
    - 10.148.0.3


spring_app:
  image: 69966/springgradleimg:1.1.1
  app_dir: /opt/spring-upload