ping-all:
  echo "ping"
  ansible -i inventory.ini all -m ping

nfs-server:
  ansible-playbook -i inventory.ini playbooks/nfs-server.yaml

nfs-main:
  ansible-playbook -i inventory.ini playbooks/nfs-main.yaml