[all:vars]
ansible_user=tochratana
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[local]
localhost ansible_connection=local

[masters]
master02 ansible_host=34.87.70.98
master03 ansible_host=35.186.149.235


[workers]
worker01 ansible_host=34.150.48.104
worker02 ansible_host=34.92.247.6
